### ISSUE TITLE
Update Mozilla Addons link?

### ISSUE THREAD

**Issue by jrchamp** [ainspector/ainspector.github.io#1]
It looks like @jongund has released a new version of the AInspector addon that is designed for current versions of Firefox. Given that the v1.1.2 link points to a 404 page, should the link here be updated to https://addons.mozilla.org/en-US/firefox/addon/ainspector-wcag/ ?

Hope that helps!

**Comment by jongund** [comment]
@jrchamp 
Thank you for reporting this issue, we are working on a fix.
